### ISSUE TITLE
【日拱一卒】三四线城市生成可视化地图

### ISSUE THREAD

**Issue by rebootfun** [xunyun/Lower-tier_Cities_in_China#4]
知知知鸟已完成基本内容了，需要生成可视化地图，大家讨论一下教程工具吧。
[三四线城市划分](https://github.com/xunyun/Lower-tier_Cities_in_China/blob/master/%E4%BD%8E%E7%BA%BF%E5%9F%8E%E5%B8%82%E5%88%92%E5%88%86.md)

**Comment by rebootfun** [comment]
刚找到一个呈现的结果图，看一下大家心中预想的是这个样子不：http://www.xxyuanzhuo.com/c/1/2016082928.html  颜色3-5种，不需要这么细致

**Comment by rebootfun** [comment]
小黑：地图已经想了几个方案了  power bi  或者 arcgis 或者 echarts

**Comment by z-flea** [comment]
嗯嗯，结果图不错，是这个意思：）！
